# deploy.yml
---
- name: Deploy Scientific Calculator Application
  hosts: local
  become: no

  vars:
    docker_image: "smoothlake67/mini-calculator:latest"
    container_name: "scientific-calculator-app"

  tasks:
    - name: Stop and remove any existing container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Pull the latest image from Docker Hub
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Start the new container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        interactive: yes
        tty: yes
        detach: yes